# Install required packages

- name: Install epel
  yum: 
    name: epel-release
    state: latest

- name: Install mail packages
  yum: 
    name:
      - postfix
      - swaks
      - dovecot
      - dovecot-pigeonhole
      - amavisd-new
      - clamav
      - clamav-update
      - spamassassin
      - clamav-scanner
      - clamav-scanner-systemd
      - postgrey
      - pypolicyd-spf
      - libsemanage-python
    state: present

- name: Set SELinux to allow clamav to scan
  seboolean:
   name: antivirus_can_scan_system
   state: yes
   persistent: yes

- name: set selinux to permissive for now ( gives to much issues with antivirus spam etc...)
  selinux:
    policy: targeted
    state: permissive

- name: set postgrey sysconfig options
  lineinfile:
    path: /etc/sysconfig/postgrey
    regexp: '^POSTGREY_OPTS'
    line: 'POSTGREY_OPTS="--delay=60 --auto-whitelist-clients=2 --max-age=120"'

- name: symlink amavis config because default location is not native to amavis
  file:
    src: "/etc/amavisd/amavisd.conf"
    dest: "/etc/amavisd.conf"
    state: link
