- include_tasks: "centos-install-mailserver.yml"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version > '6'

- name: Ensure group "vmail" exists
  group:
    name: vmail
    gid: 5000
    state: present
    system: yes

- name: Add vmail user
  user:
    name: vmail
    comment: virtual mail user
    uid: 5000
    group: vmail
    system: yes
    home: /srv/vmail

- name: ensure drop.cidr exists
  copy:
    content: ""
    dest: /etc/postfix/drop.cidr
    force: no
    group: root
    owner: root
    mode: 0644

- name: ensure identitycheck.pcre exists
  copy:
    src: identitycheck.pcre
    dest: /etc/postfix/identitycheck.pcre
    force: no
    group: root
    owner: root
    mode: 0644
 
- name: create tag_as_foreign.re
  copy:
    content: "/^/  FILTER smtp-amavis:[127.0.0.1]:10024"
    dest: /etc/postfix/tag_as_foreign.re
    force: yes
    group: root
    owner: root
    mode: 0644

- name: create tag_as_originating.re
  copy:
    content: "/^/  FILTER smtp-amavis:[127.0.0.1]:10026"
    dest: /etc/postfix/tag_as_originating.re
    force: yes
    group: root
    owner: root
    mode: 0644

- name: generate dkim key for default amavis domain
  command: /usr/sbin/amavisd genrsa /etc/mail/{{ amavis_mydomain }}.key.pem 2048
  args:
    creates: /etc/mail/{{ amavis_mydomain }}.key.pem

- name: generate extra dkim keys for extra domains
  command: /usr/sbin/amavisd genrsa /etc/mail/{{ item.name }}.key.pem 2048
  args:
    creates: /etc/mail/{{ item.name }}.key.pem
  with_items:
    - "{{ additional_amavis_domains | default([]) }}"

- name: set filepermissions on key
  file:
    path: /etc/mail/{{ amavis_mydomain }}.key.pem
    owner: amavis
    group: amavis

- name: set filepermissions on extra keys
  file:
    path: /etc/mail/{{ item.name }}.key.pem
    owner: amavis
    group: amavis
  with_items:
    - "{{ additional_amavis_domains | default([]) }}"

- name: copy 10-master.conf 
  copy:
    src: 10-master.conf
    dest: /etc/dovecot/conf.d/10-master.conf
    force: yes
    group: root
    owner: root
    mode: 0644

- name: create main.cf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf

- name: create master.cf
  template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf

- name: create ldap_virtual_recipients.cf
  template:
    src: ldap_virtual_recipients.cf.j2
    dest: /etc/postfix/ldap_virtual_recipients.cf

- name: create ldap_virtual_aliases.cf
  template:
    src: ldap_virtual_aliases.cf.j2
    dest: /etc/postfix/ldap_virtual_aliases.cf

- name: create ldap_virtual_domains.cf
  template:
    src: ldap_virtual_domains.cf.j2
    dest: /etc/postfix/ldap_virtual_domains.cf

- name: create dovecot-ldap.conf.ext
  template:
    src: dovecot-ldap.conf.ext.j2
    dest: /etc/dovecot/dovecot-ldap.conf.ext

- name: set authmech to plain login
  lineinfile:
    path: /etc/dovecot/conf.d/10-auth.conf
    regexp: '^auth_mechanisms'
    line: 'auth_mechanisms = plain login'

- name: unset auth-system in 10-auth
  lineinfile:
    path: /etc/dovecot/conf.d/10-auth.conf
    regexp: '!include auth-system.conf.ext'
    line: '#!include auth-system.conf.ext'
    
- name: set auth-ldap in 10-auth
  lineinfile:
    path: /etc/dovecot/conf.d/10-auth.conf
    line: '!include auth-ldap.conf.ext'

- name: set dovecot log to syslog
  ini_file:
    path: /etc/dovecot/conf.d/10-logging.conf
    section: null
    option: log_path
    value: syslog

- name: set syslog facility to mail
  ini_file:
    path: /etc/dovecot/conf.d/10-logging.conf
    section: null
    option: syslog_facility
    value: mail

- name: log failed login
  ini_file:
    path: /etc/dovecot/conf.d/10-logging.conf
    section: null
    option: auth_verbose
    value: 'yes'

- name: set postmaster address in dovecot
  ini_file:
    path: /etc/dovecot/conf.d/15-lda.conf
    section: null
    option: postmaster_address
    value: "{{ postmaster_address }}"

- name: enable mail plugin sieve for lda
  lineinfile:
    path: /etc/dovecot/conf.d/15-lda.conf
    insertafter: '^protocol lda '
    line: '  mail_plugins = $mail_plugins sieve'

- name: copy 15-mailboxes.conf
  copy: src=15-mailboxes.conf dest=/etc/dovecot/conf.d/15-mailboxes.conf owner=root group=root mode=644

- name: enable sieve
  ini_file:
    path: /etc/dovecot/conf.d/20-managesieve.conf
    section: null
    option: protocols
    value: $protocols sieve

- name: set sieve_before to /etc/dovecot/sieve ( for move jurnk to spamfolder)
  lineinfile:
    path: /etc/dovecot/conf.d/90-sieve.conf
    insertafter: '#sieve_before'
    line: '  sieve_before = /etc/dovecot/sieve'

- name: create sieve global dir
  file:
    path: /etc/dovecot/sieve
    state: directory
    owner: vmail
    group: vmail
    mode: 0755

- name: make sieve rule for spam
  copy:
   src: global.sieve
   dest: /etc/dovecot/sieve/global.sieve
   group: vmail
   owner: vmail
   mode: 0644

- name: create amavisd config
  template:
    src: amavisd.conf.j2
    dest: /etc/amavisd/amavisd.conf

- name: start and enable dovecot
  service:
   name: dovecot
   enabled: yes
   state: started

- name: start and enable spamassassin
  service:
   name: spamassassin
   enabled: yes
   state: started

- name: start and enable amavisd
  service:
   name: amavisd
   enabled: yes
   state: started

- name: start and enable postgrey
  service:
    name: postgrey
    enabled: yes
    state: started

- name: show dkim public key
  command: "/usr/sbin/amavisd showkeys"
  register: dkim_key

- name: show dkim public key
  debug: var=dkim_key.stdout_lines
