# Install required packages

- name: Install epel
  yum: 
    name: epel-release
    state: latest


- name: add MariaDB repo
  yum_repository:
    name: MariaDB
    description: Official MariaB Repo
    baseurl: http://yum.mariadb.org/10.3/centos7-amd64
    gpgcheck: yes
    enabled: yes
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB

- name: Install remi repo.
  yum:
    name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    state: present

- name: Import remi key
  rpm_key:
    key: "http://rpms.remirepo.net/RPM-GPG-KEY-remi"
    state: present

- name: Install Packages for roundcube
  yum: 
    name:
      - MariaDB-server
      - MariaDB-client
      - php72-php
      - php72-php-fpm
      - php72-php-dom
      - php72-php-zip
      - php72-php-gd
      - php72-php-mbstring
      - php72-php-posix
      - php72-php-opcache
      - php72-php-mysql
      - php72-php-pecl-redis
      - php72-php-ldap
      - php72-php-intl
      - php72-php-pecl-imagick 
      - nginx
      - certbot 
      - certbot-nginx
      - unzip
      - MySQL-python
      - lbzip2

- name: (roundcube centos) create roundcube opcache dir
  file:
    path: /var/opt/remi/php72/lib/php/roundcube_opcache
    state: directory
    owner: roundcube
    group: roundcube
    recurse: yes
    mode: 0770

- name: (roundcube centos) create roundcube wsdl dir
  file:
    path: /var/opt/remi/php72/lib/php/roundcube_wsdlcache
    state: directory
    owner: roundcube
    group: roundcube
    recurse: yes
    mode: 0770

- name: (roundcube centos) create roundcube session dir
  file:
    path: /var/opt/remi/php72/lib/php/roundcube_session
    state: directory
    owner: roundcube
    group: roundcube
    recurse: yes
    mode: 0770

- name: (roundcube centos) create roundcube php-fpm config
  template:
    src: roundcube_php72-fpm.conf.j2
    dest: /etc/opt/remi/php72/php-fpm.d/roundcube-php72-fpm.conf

- name: (roundcube centos) delete default www fpm
  file:
    path: /etc/opt/remi/php72/php-fpm.d/www.conf
    state: absent

- name: (roundcube centos) start php72-fpm
  systemd:
     name: php72-php-fpm
     state: restarted
     enabled: yes

- name: (roundcube centos) start mariadb
  systemd:
    name: mariadb
    state: started
    enabled: yes
