# Install required packages

- name: Install epel
  yum: 
    name: epel-release
    state: latest

- name: add zpush repo
  yum_repository:
    name: Z-Push
    description: Z-Push noarch Enterprise Linux 7 - $basearch
    baseurl: http://repo.z-hub.io/z-push:/final/RHEL_7
    gpgcheck: no
    enabled: yes

- name: Install Packages for zpush 
  yum: 
    name:
      - php-fpm
      - z-push-backend-caldav 
      - z-push-backend-carddav
      - z-push-backend-combined  
      - z-push-backend-imap      
      - z-push-common            
      - z-push-config-nginx      
      - z-push-ipc-sharedmemory    
      - z-push-autodiscover
      - php-pdo
      - php-xml
      
- name: (zpush centos) Add z-push user
  user:
    name: z-push
    comment: z-push user
    uid: 5002
    group: z-push
    system: yes
    home: /var/www/z-push

- name: (zpush centos) create zpush session dir
  file:
    path: /var/lib/php/session_zpush
    state: directory
    owner: z-push
    group: z-push
    recurse: yes
    mode: 0770

- name: (zpush centos) create zpush php config
  template:
    src: zpush-php-fpm.j2
    dest: /etc/php-fpm.d/zpush-fpm.conf

- name: (zpush centos) start php-fpm
  systemd:
     name: php-fpm
     state: started
     enabled: yes


